name: CI .NET DEV

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --no-restore
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with: 
        name: BuildArtifactDEV
        path: D:\a\CIDemo\CIDemo\bin\Debug\net5.0\publish\
